#!/home/msieur-gab/soniq-lab/venv/bin/python3
"""Rebuild _corpus_stats.py from a database.

Reads all done tracks, computes (mean, std) for every scalar feature,
and writes py/classifiers/_corpus_stats.py with the results.

This is the single source of truth — no more embedded _STATS dicts.

Usage:
    python3 rebuild_corpus_stats.py                     # from soniq_0.6.db
    python3 rebuild_corpus_stats.py --db soniq_0.5.db   # from specific DB
    python3 rebuild_corpus_stats.py --preview            # print, don't write
"""

import json
import os
import sqlite3
import sys
from datetime import date
from pathlib import Path

import numpy as np


DB_DEFAULT = Path(__file__).parent / "soniq_0.6.db"
OUTPUT = Path(__file__).parent / "py" / "classifiers" / "_corpus_stats.py"

# Features used by classifiers (from _features.py prepare())
# Only include features that classifiers actually reference
FEATURES = [
    "bandwidth", "bandwidth_std", "bass_ratio", "beat", "beat_regularity",
    "centroid", "centroid_std", "dyn_range", "flatness", "flux", "flux_std",
    "harm_energy", "harm_fraction", "harm_perc_ratio",
    "low_energy_rate", "mfcc_delta_var", "mfcc_delta2_var",
    "mid_ratio", "mod_centroid", "mod_crest", "mod_flatness", "mode",
    "onset", "onset_rate", "perc_energy",
    "plp_mean", "plp_stability", "rhythm_complexity",
    "rms_max", "rms_mean", "rms_var",
    "rolloff", "rolloff_std",
    "spectral_crest", "spectral_entropy",
    "tempo", "treble_ratio", "vocal", "zcr",
    # v0.6 additions
    "chroma_major_corr",
    "voice_band_ratio",
]


def compute_stats(db_path):
    """Compute (mean, std) for each feature across all done tracks."""
    conn = sqlite3.connect(str(db_path))
    cur = conn.cursor()
    cur.execute("SELECT scalars_json FROM tracks WHERE status='done' AND scalars_json IS NOT NULL")

    feature_values = {f: [] for f in FEATURES}

    rows = cur.fetchall()
    for (sj,) in rows:
        try:
            scalars = json.loads(sj)
        except (json.JSONDecodeError, TypeError):
            continue

        for feat in FEATURES:
            val = scalars.get(feat)
            if val is not None and isinstance(val, (int, float)):
                feature_values[feat].append(float(val))

    conn.close()

    stats = {}
    for feat in FEATURES:
        vals = feature_values[feat]
        if len(vals) > 10:
            stats[feat] = (round(float(np.mean(vals)), 4), round(float(np.std(vals)), 4))
        else:
            print(f"  WARNING: {feat} has only {len(vals)} values — skipped")

    return stats, len(rows)


def write_stats_file(stats, n_tracks, db_name):
    """Write _corpus_stats.py with computed stats."""
    lines = [
        '"""Corpus statistics for formula-based classifiers.',
        "",
        f"Bootstrap stats (mean, std) from {db_name} (N={n_tracks}).",
        "All classifiers use these for z-score normalization via _norm().",
        "",
        "Generated by rebuild_corpus_stats.py — do not edit manually.",
        '"""',
        "",
        f"# (mean, std) tuples — computed from {n_tracks} tracks, {date.today().isoformat()}",
        "STATS = {",
    ]

    # Find longest key for alignment
    max_key = max(len(f'"{k}"') for k in stats)

    for feat in sorted(stats.keys()):
        mean, std = stats[feat]
        key_str = f'"{feat}"'
        lines.append(f"    {key_str:<{max_key + 1}}: ({mean}, {std}),")

    lines.append("}")
    lines.append("")  # trailing newline

    return "\n".join(lines)


if __name__ == "__main__":
    db_path = DB_DEFAULT
    preview = False

    args = sys.argv[1:]
    i = 0
    while i < len(args):
        if args[i] == "--preview":
            preview = True
        elif args[i] == "--db" and i + 1 < len(args):
            db_path = Path(args[i + 1])
            i += 1
        elif args[i] in ("--help", "-h"):
            print(__doc__)
            sys.exit(0)
        i += 1

    if not db_path.exists():
        print(f"  ERROR: {db_path} not found")
        sys.exit(1)

    print(f"\n  Rebuilding corpus stats from {db_path.name}...")
    stats, n_tracks = compute_stats(db_path)
    print(f"  Computed stats for {len(stats)} features from {n_tracks} tracks")

    content = write_stats_file(stats, n_tracks, db_path.name)

    if preview:
        print("\n" + content)
    else:
        with open(OUTPUT, "w") as f:
            f.write(content)
        print(f"  Written to {OUTPUT}")

    print("  Done.\n")
