"""Corpus statistics for formula-based classifiers.

Bootstrap stats (mean, std) from soniq_0.6.db (N=1708).
All classifiers use these for z-score normalization via _norm().

Generated by rebuild_corpus_stats.py — do not edit manually.
"""

# (mean, std) tuples — computed from 1708 tracks, 2026-03-16
STATS = {
    "bandwidth"         : (1780.7111, 533.177),
    "bandwidth_std"     : (385.7593, 163.2628),
    "bass_ratio"        : (0.5846, 0.2125),
    "beat"              : (2.2843, 0.8096),
    "beat_regularity"   : (6.7933, 2.3224),
    "centroid"          : (1395.4354, 609.3307),
    "centroid_std"      : (481.7789, 278.583),
    "chroma_major_corr" : (0.3818, 0.2561),
    "dyn_range"         : (16.933, 9.588),
    "flatness"          : (0.0067, 0.0113),
    "flux"              : (41.7653, 25.6674),
    "flux_std"          : (27.865, 18.0443),
    "harm_energy"       : (0.1144, 0.0558),
    "harm_fraction"     : (0.7686, 0.1118),
    "harm_perc_ratio"   : (4.4388, 2.8747),
    "low_energy_rate"   : (0.4609, 0.069),
    "mfcc_delta2_var"   : (1.3197, 0.5052),
    "mfcc_delta_var"    : (2.0826, 0.7702),
    "mid_ratio"         : (0.3792, 0.2058),
    "mod_centroid"      : (33.7058, 7.7613),
    "mod_crest"         : (80.9752, 24.0443),
    "mod_flatness"      : (0.3263, 0.0666),
    "mode"              : (0.4081, 0.4915),
    "onset"             : (2.0479, 0.6442),
    "onset_rate"        : (3.8189, 1.6172),
    "perc_energy"       : (0.0381, 0.0289),
    "plp_mean"          : (0.1823, 0.0437),
    "plp_stability"     : (0.7264, 0.0646),
    "rhythm_complexity" : (7.588, 0.0953),
    "rms_max"           : (16.0355, 5.1044),
    "rms_mean"          : (10.1886, 5.5236),
    "rms_var"           : (7.8745, 18.2226),
    "rolloff"           : (2808.9242, 1418.4316),
    "rolloff_std"       : (1163.5491, 623.8044),
    "spectral_crest"    : (87.7957, 31.0716),
    "spectral_entropy"  : (3.9241, 0.6487),
    "tempo"             : (119.2781, 30.4835),
    "treble_ratio"      : (0.0362, 0.0608),
    "vocal"             : (0.7243, 0.1669),
    "voice_band_ratio"  : (0.3599, 0.2476),
    "zcr"               : (0.0565, 0.0318),
}
