"""Corpus statistics for formula-based classifiers.

Bootstrap stats (mean, std) from soniq_0.7.db (N=1942).
All classifiers use these for z-score normalization via _norm().

Generated by rebuild_corpus_stats.py — do not edit manually.
"""

# (mean, std) tuples — computed from 1942 tracks, 2026-03-17
STATS = {
    "bandwidth_std"     : (369.4729, 158.2748),
    "beat"              : (2.4761, 0.7993),
    "beat_regularity"   : (6.3034, 2.1274),
    "centroid"          : (1530.3513, 610.4227),
    "centroid_std"      : (478.5994, 256.1255),
    "chroma_major_corr" : (0.3932, 0.2533),
    "flatness"          : (0.0107, 0.0268),
    "flux"              : (70.7763, 40.2381),
    "flux_std"          : (41.8509, 24.7448),
    "harm_energy"       : (0.1845, 0.0892),
    "harm_fraction"     : (0.7581, 0.1033),
    "mfcc_delta_var"    : (2.011, 0.691),
    "mod_crest"         : (84.4229, 23.7602),
    "mode"              : (0.4212, 0.4938),
    "onset"             : (2.1955, 0.6242),
    "onset_rate"        : (4.139, 1.5976),
    "perc_energy"       : (0.064, 0.0447),
    "plp_stability"     : (0.7359, 0.0599),
    "rhythm_complexity" : (7.5906, 0.1906),
    "rms_mean"          : (14.2293, 7.6715),
    "rms_var"           : (26.3741, 37.5029),
    "tempo"             : (121.0471, 28.6227),
    "treble_ratio"      : (0.043, 0.0559),
}
